%% Make a spectrum string with reflectance in a single band.
% like '300:0 499:0 500:1 501:0 800:0'
function reflectance = GetSingleBandReflectance(wls, whichBand, background, inBand)
low = wls(1);
target = wls(whichBand);
high = wls(end);
leftFlank = target-1;
rightFlank = target+1;
reflectance = sprintf('%d:%d %d:%d %d:%d %d:%d %d:%d', ...
    low, background, ...
    leftFlank, background, ...
    target, inBand, ...
    rightFlank, background, ...
    high, background);
