%% Assemble processed images into a handy montage.
%   recipe should be a recipe from BuildWardLandRecipe()
%   scaleFactor should be a scalar for the montage size (could be large)
%   scaleMethod should be a filtering method like (box)
function recipe = MakeRecipeImageMontage(recipe, scaleFactor, scaleMethod)

if nargin < 2 || isempty(scaleFactor)
    scaleFactor = getpref('VirtualScenes', 'montageScaleFactor');
end

if nargin < 3 || isempty(scaleMethod)
    scaleMethod = getpref('VirtualScenes', 'montageScaleMethod');
end

% choose images to assemble
images = { ...
    recipe.processing.srgb.main, ...
    recipe.processing.srgb.matte, ...
    recipe.processing.srgb.specular; ...
    recipe.processing.maskCoverageFile, ...
    '', ...
    recipe.processing.srgb.diffuseReflectanceInterp; ...
    recipe.processing.boring.radiance, ...
    recipe.processing.srgb.diffuseIlluminationInterp, ...
    recipe.processing.srgb.diffuseIlluminationMeanInterp; ...
    };

% choose a name for each panel
names = { ...
    'main radiance', ...
    'diffuse radiance', ...
    'specular radiance'; ...
    'mask coverage', ...
    '', ...
    'diffuse reflectance'; ...
    'boring radiance', ...
    'diffuse illumination', ...
    'diffuse mean illumination', ......
    };

% write out a big montage
imageFolder = GetWorkingFolder('images', true, recipe.input.hints);
recipe.processing.montage = MakeImageMontage( ...
    fullfile(imageFolder, 'montage.png'), images, names, scaleFactor, scaleMethod);
