%% Assemble processed images into a handy montage.
%   @param recipe a recipe from BuildWardLandRecipe()
%   @param scaleFactor a scalar for the montage size (could be large)
%   @param scaleMethod a filtering method like (box)
%
% @details
% Combines several of the WardLand rendered and processed images for the
% given @a recipe into a large summary montage.  Panels in the montage will
% be labeled.
%
% @details
% @a scaleFactor and @a scaleMethod can be used to scale entire montage,
% for example if it would be very large.  The default scale factor and
% filtering method are from getpref('VirtualScenes', 'montageScaleFactor')
% and getpref('VirtualScenes', 'montageScaleMethod').
%
% @details
% Returns the given @a recipe, updated with a new montage image
%   - recipe.processing.montage will contain the name of a new image file
%   for the new montage.
%   .
% @details
% Usage:
%   recipe = MakeRecipeImageMontage(recipe, scaleFactor, scaleMethod)
%
% @ingroup WardLand
function recipe = MakeRecipeImageMontage(recipe, scaleFactor, scaleMethod)

if nargin < 2 || isempty(scaleFactor)
    scaleFactor = getpref('VirtualScenes', 'montageScaleFactor');
end

if nargin < 3 || isempty(scaleMethod)
    scaleMethod = getpref('VirtualScenes', 'montageScaleMethod');
end

% choose images to assemble
images = { ...
    recipe.processing.srgb.main, ...
    recipe.processing.srgb.matte, ...
    recipe.processing.srgb.specular; ...
    recipe.processing.maskCoverageFile, ...
    '', ...
    recipe.processing.srgb.diffuseReflectanceInterp; ...
    recipe.processing.boring.radiance, ...
    recipe.processing.srgb.diffuseIlluminationInterp, ...
    recipe.processing.srgb.diffuseIlluminationMeanInterp; ...
    };

% choose a name for each panel
names = { ...
    'main radiance', ...
    'diffuse radiance', ...
    'specular radiance'; ...
    'mask coverage', ...
    '', ...
    'diffuse reflectance'; ...
    'boring radiance', ...
    'diffuse illumination', ...
    'diffuse mean illumination', ......
    };

% write out a big montage
imageFolder = GetWorkingFolder('images', true, recipe.input.hints);
recipe.processing.montage = MakeImageMontage( ...
    fullfile(imageFolder, 'montage.png'), images, names, scaleFactor, scaleMethod);
