% Convert some illumination and reflectance images to LMS representations.
%   recipe should be a recipe from BuildVirtualSceneRecipe
%   matchingFunctions should be a Psychtoolbox colorimetric mat-file name
function recipe = MakeRecipeLMSImages(recipe, matchingFunctions)

if nargin < 2 || isempty(matchingFunctions)
    matchingFunctions = 'T_cones_ss2.mat';
end

% where to write out new images
imageFolder = GetWorkingFolder('images', true, recipe.input.hints);

% compute LMS for diffuse illumination
recipe.processing.lms.diffuseIlluminationInterp = ...
    computeLMS('diffuseIlluminationInterp', ...
    recipe.processing.multispectral.diffuseIlluminationInterp, ...
    recipe.processing.multispectral.S, ...
    matchingFunctions, ...
    imageFolder);

% compute LMS for diffuse illumination, mean per object
recipe.processing.lms.diffuseIlluminationMeanInterp = ...
    computeLMS('diffuseIlluminationMeanInterp', ...
    recipe.processing.multispectral.diffuseIlluminationMeanInterp, ...
    recipe.processing.multispectral.S, ...
    matchingFunctions, ...
    imageFolder);

% compute LMS for diffuse reflectance
recipe.processing.lms.diffuseReflectanceInterp = ...
    computeLMS('diffuseReflectanceInterp', ...
    recipe.processing.multispectral.diffuseReflectanceInterp, ...
    recipe.processing.multispectral.S, ...
    matchingFunctions, ...
    imageFolder);

function lmsData = computeLMS(name, multispectral, S, matchingFunctions, imageFolder)
% compute actual LMS sensor image
lmsData.sensorImage = ...
    MultispectralToSensorImage(multispectral, S, matchingFunctions);

sensorMax = max(lmsData.sensorImage(:));

% write out L, M, and S channels to disk
lmsData.l = WriteImage( ...
    fullfile(imageFolder, 'lms', [name '-l.png']), ...
    lmsData.sensorImage(:,:,1) ./ sensorMax);

lmsData.m = WriteImage( ...
    fullfile(imageFolder, 'lms', [name '-m.png']), ...
    lmsData.sensorImage(:,:,2) ./ sensorMax);

lmsData.s = WriteImage( ...
    fullfile(imageFolder, 'lms', [name '-s.png']), ...
    lmsData.sensorImage(:,:,3) ./ sensorMax);

