% Get typical mapping file configuration descriptsions for some renderers.
function configs = GetRendererConfigs()

%% Mitsuba
integratorId = 'integrator';
samplerId = 'Camera-camera_sampler';
configs.Mitsuba.ids = {integratorId, samplerId};

% Mitsuba "full" rendering config
fullIntegrator = BuildDesription('integrator', 'path', ...
    {'maxDepth'}, ...
    {'10'}, ...
    {'integer'});
fullSampler = BuildDesription('sampler', 'ldsampler', ...
    {'sampleCount'}, ...
    {'128'}, ...
    {'integer'});
configs.Mitsuba.full.descriptions = {fullIntegrator, fullSampler};
configs.Mitsuba.full.blockName = 'Mitsuba';

% Mitsuba "quick" rendering config
quickIntegrator = BuildDesription('integrator', 'direct', ...
    {'shadingSamples'}, ...
    {'32'}, ...
    {'integer'});
quickSampler = BuildDesription('sampler', 'ldsampler', ...
    {'sampleCount'}, ...
    {'32'}, ...
    {'integer'});
configs.Mitsuba.quick.descriptions = {quickIntegrator, quickSampler};
configs.Mitsuba.quick.blockName = 'Mitsuba';

%% PBRT
integratorId = 'integrator';
samplerId = 'sampler';
configs.PBRT.ids = {integratorId, samplerId};

% PBRT "full" rendering config
fullIntegrator = BuildDesription('SurfaceIntegrator', 'path', ...
    {'maxdepth'}, ...
    {'1'}, ...
    {'integer'});
fullSampler = BuildDesription('Sampler', 'lowdiscrepancy', ...
    {'pixelsamples'}, ...
    {'8'}, ...
    {'integer'});
configs.PBRT.full.descriptions = {fullIntegrator, fullSampler};
configs.PBRT.full.blockName = 'PBRT';

% Mitsuba "quick" rendering config
quickIntegrator = BuildDesription('SurfaceIntegrator', 'directlighting', ...
    {'maxdepth'}, ...
    {'1'}, ...
    {'integer'});
quickSampler = BuildDesription('Sampler', 'lowdiscrepancy', ...
    {'pixelsamples'}, ...
    {'8'}, ...
    {'integer'});
configs.PBRT.quick.descriptions = {quickIntegrator, quickSampler};
configs.PBRT.quick.blockName = 'PBRT';
