%% Test writing and reading metadata for a few models.

clear
clc

%% IndoorPlant base scene
modelName = 'IndoorPlant';
boundingVolume = [-6 2; -2 2; 0 6];
materialIds = { ...
    'BaseBoard-material', ...
    'Floor-material', ...
    'Leaves-material', ...
    'Lights-material', ...
    'Pot-material', ...
    'Rocks-material', ...
    'Wall-material', ...
    };
lightIds = { ...
    'CeilingLight-mesh', ...
    'HighRearLight-mesh', ...
    'LowRearLight-mesh', ...
    };
metadata = WriteMetadata(modelName, boundingVolume, materialIds, lightIds);
readMetadata = ReadMetadata(modelName);
assert(isequal(metadata, readMetadata))

%% Warehouse base scene
modelName = 'Warehouse';
boundingVolume = [-12 -2; -3 6; 0 3];
materialIds = { ...
    'AreaLight-material', ...
    'Barrel01-material', ...
    'Barrel02-material', ...
    'Bars-material', ...
    'Bottle01-material', ...
    'Bottle02-material', ...
    'Can01-material', ...
    'Can02-material', ...
    'Ground-material', ...
    'Metal-material', ...
    'Roof-material', ...
    'Sign01-material', ...
    'Sign02-material', ...
    'Sign03-material', ...
    'Stick-material', ...
    'Wall-material', ...
    'Wood01-material', ...
    'Wood02-material', ...
    };
lightIds = { ...
    'Sun-mesh', ...
    'Sky-mesh', ...
    'OutsideLight-mesh', ...
    'WindowLight-mesh', ...
    'CeilingLight-mesh', ...
    };
metadata = WriteMetadata(modelName, boundingVolume, materialIds, lightIds);
readMetadata = ReadMetadata(modelName);
assert(isequal(metadata, readMetadata))

%% Barrel object
modelName = 'Barrel';
materialIds = { ...
    'Material01-material', ...
    };
metadata = WriteMetadata(modelName, [], materialIds);
readMetadata = ReadMetadata(modelName);
assert(isequal(metadata, readMetadata))

%% ChampagneBottle object
modelName = 'ChampagneBottle';
materialIds = { ...
    'Material01-material', ...
    };
metadata = WriteMetadata(modelName, [], materialIds);readMetadata = ReadMetadata(modelName);
assert(isequal(metadata, readMetadata))

%% RingToy object
modelName = 'RingToy';
materialIds = { ...
    'Material01-material', ...
    'Material02-material', ...
    'Material03-material', ...
    'Material04-material', ...
    'Material05-material', ...
    'Material06-material', ...
    };
metadata = WriteMetadata(modelName, [], materialIds);
readMetadata = ReadMetadata(modelName);
assert(isequal(metadata, readMetadata))

%% Xylophone object
modelName = 'Xylophone';
materialIds = { ...
    'Material01-material', ...
    'Material02-material', ...
    'Material03-material', ...
    };
metadata = WriteMetadata(modelName, [], materialIds);readMetadata = ReadMetadata(modelName);
assert(isequal(metadata, readMetadata))
